# Generated by Django 5.0.6 on 2024-05-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
        ("tienda", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "ordering": ["id"],
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
            },
        ),
        migrations.AlterModelTable(
            name="pedido",
            table="pedidos",
        ),
        migrations.CreateModel(
            name="LineaPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedidos.pedido"
                    ),
                ),
                (
                    "producto_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.producto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Linea Pedido",
                "verbose_name_plural": "Lineas Pedidos",
                "db_table": "lineapedidos",
                "ordering": ["id"],
            },
        ),
    ]
