# Generated by Django 5.0.6 on 2024-05-19 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0002_alter_pedido_options_alter_pedido_table_lineapedido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineapedido",
            old_name="pedido_id",
            new_name="pedido_id_id",
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="producto_id",
            new_name="producto_id_id",
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="usr",
            new_name="user",
        ),
    ]
