# Generated by Django 5.0.6 on 2024-05-19 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0003_rename_pedido_id_lineapedido_pedido_id_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineapedido",
            old_name="pedido_id_id",
            new_name="pedido",
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="producto_id_id",
            new_name="producto",
        ),
    ]
